### ISSUE TITLE
Initial figure

### ISSUE THREAD

**Issue by YitengD** [YitengD/Multicellularity#2]
The initial configuration shows an empty graph rather than a lattice of cells. Is it possible to start with a lattice of cells instead?
![Screenshot](https://github.com/YitengD/Multicellularity/blob/master/issue%20screenshots/initial_graph.png)

**Comment by MarcelBrusius** [comment]
This is how the graph looks like right after opening the app. Pull request follows.

![matlabwindow_2018-01-06_23-10-25](https://user-images.githubusercontent.com/22997398/34644430-cc9987e0-f336-11e7-86c6-3297417714cb.png)
